// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return ios;
      default:
        return android;
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.get('FIREBASE_API_KEY'),
    appId: '1:153655535342:web:50c68ff1f226d09f9275ff',
    messagingSenderId: '153655535342',
    projectId: 'dongmai-26217',
    authDomain: 'dongmai-26217.firebaseapp.com',
    storageBucket: 'dongmai-26217.firebasestorage.app',
    measurementId: 'G-C6G7SS3CT0',
  );

  //static FirebaseOptions android = FirebaseOptions(
  //  apiKey: dotenv.get('FIREBASE_API_KEY'),
  //  appId: '1:153655535342:android:0597b503101f22af9275ff',
  //   messagingSenderId: '153655535342',
  //  projectId: 'dongmai-26217',
  //  storageBucket: 'dongmai-26217.firebasestorage.app',
  // );

  //static FirebaseOptions ios = FirebaseOptions(
  //  apiKey: dotenv.get('FIREBASE_API_KEY'),
  //  appId: '1:153655535342:ios:71566b95faa3a6f99275ff',
  //  messagingSenderId: '153655535342',
  // projectId: 'dongmai-26217',
  //  storageBucket: 'dongmai-26217.firebasestorage.app',
  // iosBundleId: 'com.example.gongdong',
  // );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: dotenv.get('FIREBASE_API_KEY'),
    appId: '1:153655535342:ios:71566b95faa3a6f99275ff',
    messagingSenderId: '153655535342',
    projectId: 'dongmai-26217',
    storageBucket: 'dongmai-26217.firebasestorage.app',
    iosBundleId: 'com.example.gongdong',
  );

  static FirebaseOptions windows = FirebaseOptions(
    apiKey: dotenv.get('FIREBASE_API_KEY'),
    appId: '1:153655535342:web:d9816ffe4f7438dd9275ff',
    messagingSenderId: '153655535342',
    projectId: 'dongmai-26217',
    authDomain: 'dongmai-26217.firebaseapp.com',
    storageBucket: 'dongmai-26217.firebasestorage.app',
    measurementId: 'G-RD1BK6EM3N',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY'] ?? '',
    appId: '1:153655535342:ios:71566b95faa3a6f99275ff',
    messagingSenderId: '153655535342',
    projectId: 'dongmai-26217',
    storageBucket: 'dongmai-26217.firebasestorage.app',
    iosBundleId: 'com.example.gongdong',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY'] ?? '',
    appId: '1:153655535342:android:0597b503101f22af9275ff',
    messagingSenderId: '153655535342',
    projectId: 'dongmai-26217',
    storageBucket: 'dongmai-26217.firebasestorage.app',
  );
}
